/* ================================================================================
-- TEP 1: 01_RUN_AS_SYSDBA.sql (DA SUA LOI ORA-01031)
-- CHAY VOI QUYEN: SYS AS SYSDBA
================================================================================
*/

-- Chuyen sang PDB 'PDBORCL'
ALTER SESSION SET CONTAINER = PDBORCL;
ALTER SESSION SET "_ORACLE_SCRIPT"= true;

/* ----- TAO USER QLTS ----- */
CREATE USER QLTS IDENTIFIED BY qlts
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS;

/* ----- CAP QUYEN CO BAN ----- */
-- Them WITH ADMIN OPTION de QLTS co the cap quyen nay cho role khac
GRANT CONNECT, RESOURCE TO QLTS WITH ADMIN OPTION;
GRANT CREATE VIEW, CREATE PROCEDURE, CREATE TRIGGER TO QLTS WITH ADMIN OPTION;

/* ----- CAP QUYEN MA HOA (AES, RSA) ----- */
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO QLTS;
GRANT EXECUTE ON SYS.UTL_I18N TO QLTS;
/* ----- CAP QUYEN BAO MAT NANG CAO (PROFILE, SESSION) ----- */
GRANT CREATE PROFILE TO QLTS;
GRANT CREATE TABLESPACE TO QLTS;
GRANT ALTER SYSTEM TO QLTS; -- (De kill session)
GRANT SELECT ON v_$session TO QLTS;
GRANT SELECT ON dba_free_space TO QLTS;
GRANT SELECT ON dba_data_files TO QLTS;

/* ----- CAP QUYEN QUAN LY ROLE ----- */
-- Them WITH ADMIN OPTION
GRANT CREATE USER, ALTER USER, DROP USER TO QLTS WITH ADMIN OPTION;
GRANT CREATE ROLE, DROP ANY ROLE TO QLTS WITH ADMIN OPTION;
GRANT GRANT ANY ROLE TO QLTS WITH ADMIN OPTION;

GRANT SELECT ON dba_users TO QLTS;
GRANT SELECT ON dba_roles TO QLTS;
GRANT SELECT ON dba_role_privs TO QLTS;
/* ----- CAP QUYEN CHO VPD (VIRTUAL PRIVATE DATABASE) ----- */
GRANT CREATE ANY CONTEXT TO QLTS;
GRANT EXECUTE ON SYS.DBMS_RLS TO QLTS;

/* ----- CAP QUYEN CHO FGA (GIAM SAT) & FLASHBACK (PHUC HOI) ----- */
GRANT EXECUTE ON SYS.DBMS_FGA TO QLTS;
GRANT SELECT ON DBA_FGA_AUDIT_TRAIL TO QLTS;

/* ----- CAP QUYEN CHO OLS (ORACLE LABEL SECURITY) ----- */
GRANT LBAC_DBA TO QLTS;
GRANT EXECUTE ON SA_SYSDBA TO QLTS;
GRANT EXECUTE ON SA_COMPONENTS TO QLTS;
GRANT EXECUTE ON SA_POLICY_ADMIN TO QLTS;
GRANT EXECUTE ON SA_SESSION TO QLTS;
GRANT EXECUTE ON CHAR_TO_LABEL TO QLTS;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO QLTS;
GRANT EXECUTE ON SYS.UTL_I18N TO QLTS;
GRANT EXECUTE ON SYS.UTL_RAW TO QLTS;

GRANT CREATE USER, ALTER USER, DROP USER TO QLTS;
GRANT CREATE ROLE, DROP ANY ROLE, GRANT ANY ROLE TO QLTS;
GRANT ALTER SYSTEM TO QLTS;

/* Luu lai tat ca cac quyen */
COMMIT;
GRANT CREATE SYNONYM TO QLTS;

/* Luu lai quyen */
COMMIT;